version: "2"
services:

  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    user: "${UID}:${GID}"
    environment:
      - MYSQL_DATABASE=todos
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456789
      - MYSQL_HOST=db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456789
      - MYSQL_DATABASE=todos
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./docker/mysql/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: { driver: local }
